// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC4Q_hL5XrBPyQOCb3c4JG7-N7qD3vbuQs',
    appId: '1:539393737929:web:6eb1a72f5680c849cab918',
    messagingSenderId: '539393737929',
    projectId: 'chat-app-58d54',
    authDomain: 'chat-app-58d54.firebaseapp.com',
    storageBucket: 'chat-app-58d54.firebasestorage.app',
    measurementId: 'G-Y1NZ77M1D4',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCexZenO5rAidE5PDDLaQgWrxDKglXN-ZU',
    appId: '1:539393737929:android:2fedf764ec87af3ecab918',
    messagingSenderId: '539393737929',
    projectId: 'chat-app-58d54',
    storageBucket: 'chat-app-58d54.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC-45J2ff0JQDYdIT2QHPlDJmw6kVBlP6Q',
    appId: '1:539393737929:ios:9f9d1dc98871ad0ccab918',
    messagingSenderId: '539393737929',
    projectId: 'chat-app-58d54',
    storageBucket: 'chat-app-58d54.firebasestorage.app',
    iosBundleId: 'com.example.chatapp',
  );

}